---
- name: Generate key files
  user:
    name: "{{ osp_username }}"
    # name: "{{ ansible_env.USER }}"
    generate_ssh_key: true
    ssh_key_file: .ssh/test_id_rsa

- name: Create OSP keypair
  os_keypair:
    cloud: ospcloud
    state: present
    name: ansible_ssh
    public_key_file: "{{ osp_user_home }}/.ssh/test_id_rsa.pub"
